# Generated by Django 4.2.20 on 2025-04-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('trade_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
